spring.application.name: spring-customer-app

management:
  metrics:
    export:
      datadog:
        api-key: ${DATADOG_API_KEY}
        application-key: ${DATADOG_APPLICATION_KEY}
        host-tag: ${spring.application.name}.voicestreams.com
        step: 2s